# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9876
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
  - port: 3004
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: export NG_CLI_ANALYTICS=ci
    init: npm install
    command: >
      cd ./web &&
      npm i -g json-server &&
      npm i json-server &&
      npm i -D json-server json-server-auth &&
      json-server db.json -m ./node_modules/json-server-auth --watch --port 3004
  - command: >
      echo n | npm i -g @angular/cli@9.1.9 && 
      npm i -g jshint && 
      npm i -g tslint
  - command: >
      cd ./web &&
      sleep 2 &&
      echo n | npm i @angular/cli@9.1.9 && 
      sleep 6 &&
      ng serve --host 0.0.0.0 --disableHostCheck
# Github config
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false

# Command to add your extensions
vscode:
  extensions:
    - vscode-icons-team.vscode-icons@9.7.0:vWMZFN0zy+UAVL2V5iuz4A==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - Zignd.html-css-class-completion@1.19.0:Soyzg8syqQX3vm86CKnPtg==
    - dbaeumer.jshint@0.10.21:v0Z+15O8OAtQO18JkUDiew==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - johnpapa.Angular2@9.1.2:uM4PeIXJe98IILNHmOn+nA==
    - esbenp.prettier-vscode@5.0.1:RwSu+IlJT2eB3vwdygaJUQ==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - ecmel.vscode-html-css@0.2.3:hh8R73s3n0g/eQ8EL9PatQ==
    - Mikael.Angular-BeastCode@8.1.1:zs+UbkVfAHEN0GF4MPvEKA==
    - Angular.ng-template@0.901.11:QCtJbOimfoJnIn3365jl8A==
    - anseki.vscode-color@0.4.5:6L3EhKJFHuizA7wqZz6/+g==
    - steoates.autoimport@1.5.3:Tr3qYUEEq73wrKwCWaYivQ==
    - formulahendry.auto-close-tag@0.5.7:ofk2Iz4wGQdoTFrnRwzI7w==
    - humao.rest-client@0.24.1:UhapLZmNlh7QrJ3eHW+tpg==
