// Doc - https://github.com/Huachao/vscode-restclient/blob/master/README.md
// https://www.mockable.io/
@baseUrl = http://demo0956902.mockable.io


####### login - auth
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "admin@email.com",
  "password": "12345"
}

###

####### users - add users
# @name users
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "admin@email.com",
  "password": "12345",
  "firstName": "Admin"
}

###

####### users - list of users
# @name users
GET {{baseUrl}}/users HTTP/1.1
Content-Type: application/json; charset=utf-8

###

####### financial-assets - list of financial-assets
# @name financial-assets
GET {{baseUrl}}/financial-assets HTTP/1.1
Content-Type: application/json; charset=utf-8

###